### ISSUE TITLE
README not readable in dark mode

### ISSUE THREAD

**Issue by bertdv** [biaslab/ReactiveMP.jl#93] opened 2022-04-17 08:56 UTC
In dark mode, the equations in dark mode are not readable. 

[](url
![Screenshot 2022-04-17 at 10 53 29](https://user-images.githubusercontent.com/3426064/163707690-d64a7fa0-a576-4193-a585-6f7037060c36.png)
)

**Comment by bvdmitri** [comment] 2022-04-17 16:01
Hey Bert, thanks! We have a similar issue already #71. See the discussion why it is not that easy to fix. I tried to find a solution, but back then it was not doable. We might try to find a solution again, maybe GitHub supports it now.

**Comment by bvdmitri** [comment] 2022-04-25 09:32
Closed as duplicate of #71 .

**Closed by bvdmitri** 2022-04-25 09:32 UTC
