### ISSUE TITLE
Revision of approximations

### ISSUE THREAD

**Issue by albertpod** [biaslab/ReactiveMP.jl#276] opened 2023-02-22 12:36 UTC
The issue at hand pertains to the `ReactiveMP.jl `folder named `approximations/`, which is growing and being poorly maintained.
In essence, approximation methods should not be included in message-passing since they are semantically distinct entities.
The proposed solution is to enhance and relocate the `approximation/ `folder within `ExpectationApproximations.jl`

**Comment by bartvanerp** [comment] 2023-02-22 13:11
Is this a duplicate of #27?

**Closed** 2023-02-22 13:17 UTC
Labels: enhancement
